stages:
  - build
  - test
  - deploy

file_generation:
  tags:
    - DevOpsShell
  stage: build
  script:
    - convert lab02/vector.jpg -bordercolor black -border 3 -bordercolor white -border 2 -background black -fill white -pointsize 24 label:"'это $CI_COMMIT_AUTHOR' в '$CI_JOB_STARTED_AT'" -trim +repage -bordercolor black -border 10 -gravity South -append -bordercolor black -border 10 -gravity South -chop 0x10 lab02/meme.jpg
  artifacts:
    untracked: true
    paths:
      - lab02/meme.jpg
    expire_in: 1 day

configuration_checking:
  tags:
    - DevOpsShell
  stage: test
  dependencies:
    - file_generation
  script:
    - sudo nginx -t

deploying:
  tags:
    - DevOpsShell
  stage: deploy
  dependencies:
    - file_generation
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    # на сервере-получателе: sudo chown user /etc/nginx/sites-enabled/default
    - sudo sshpass -p $sudo_password scp lab02/default2 user@192.168.3.72:/etc/nginx/sites-enabled/default
    # там же: mkdir ~/devops && ~/devops/lab02
    - sudo sshpass -p $sudo_password scp lab02/vector.jpg user@192.168.3.72:~/devops/lab02/vector.jpg
    - sudo sshpass -p $sudo_password scp lab02/meme.jpg user@192.168.3.72:~/devops/lab02/meme.jpg
    # после переноса файлов: sudo chmod -R 777 /home/user
