stages:
  - build
  - test
  - deploy

file_generation:
  tags:
    - DevOpsShell
  stage: build
  script:
    - tpage --define start_time=$CI_JOB_STARTED_AT --define com_time=$CI_JOB_URL lab02/main.html

checking_configuration:
  tags:
    - DevOpsShell
  stage: test
  script:
    - sudo nginx -t

#test-code-job2:
#  stage: test
#  script:
#    - echo "If the files are built successfully, test other files with a different command:"
#    - rake test2
