stages:
  - build
  - test
  - deploy

file_generation:
  tags:
    - DevOpsShell
  stage: build
  script:
    - convert lab02/vector.jpg -bordercolor black -border 3 -bordercolor white -border 2 -background black -fill white -pointsize 24 label:"а '$CI_COMMIT_AUTHOR' матрица" -trim +repage -bordercolor black -border 10 -gravity South -append -bordercolor black -border 10 -gravity South -chop 0x10 lab02/meme.jpg
  artifacts:
    paths:
      - lab02/meme.jpg
    expire_in: 5 mins

configuration_checking:
  tags:
    - DevOpsShell
  stage: test
  script:
    - sudo nginx -t

deploying:
  tags:
    - DevOpsShell
  stage: deploy
  dependencies:
    - file_generation
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    # sudo chown {имя пользователя на сервера-получателе} /etc/nginx/sites-enabled/default
    - sudo sshpass -p $sudo_password scp -r lab02/default2 user@192.168.3.72:/etc/nginx/sites-enabled/default
    # на сервере-получателе: mkdir ~/devops && ~/devops/lab02
    - sudo sshpass -p $sudo_password scp -r lab02/vector.jpg user@192.168.3.72:~/devops/lab02/vector.jpg
    #- curl -o lab/02 --location --form "job-token='$CI_JOB_TOKEN'" "https://git.iu7.bmstu.ru/api/v4/projects/5516/jobs/'$CI_JOB_ID'/artifacts"
    - sudo sshpass -p $sudo_password scp -r lab02/meme.jpg user@192.168.3.72:~/devops/lab02/meme.jpg
