stages:
  - build
  - test
  - deploy

file_generation:
  tags:
    - DevOpsShell
  stage: build
  before_script:
    - sudo apt-get install libtemplate-perl
  script:
    - tpage --define start_time=$CI_JOB_STARTED_AT --define com_time=$CI_JOB_URL lab02/main.html > lab02/main.html
  only:
    - schedules

checking_configuration:
  tags:
    - DevOpsShell
  stage: test
  script:
    - sudo nginx -t
  only:
    - schedules

#test-code-job2:
#  stage: test
#  script:
#    - echo "If the files are built successfully, test other files with a different command:"
#    - rake test2
